# Use root/root as user/password or mysql/admin for credentials 
version: '3.3'

services:
  #web:
  #  build: .
  #  ports:
  #    - 8000:8000
  
  #web:
  #  image: nginx:1.23.2-alpine
  #  networks: 
  #   - sporty-shoes.net
  #  ports: 
  #    - 8087:8080

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sporty-shoes.db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mysql'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    networks: 
      - sporty-shoes.net

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3308:3306      
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - sporty-shoes.db:/var/lib/mysql

  sporty-shoes:
    #image: brianharmon1970/sporty-shoes
    image: ss-ubuntu
    #restart: always
    networks: 
      - sporty-shoes.net
    ports:
      - 8087:8080
    expose:
      - 8080

networks:
  sporty-shoes.net:
    driver: bridge
   
# Names our volume
volumes:
  sporty-shoes.db:

