FROM openjdk:18
COPY ./target/SportyShoes-0.0.1-SNAPSHOT.jar /usr/src/sportyshoes/sportyshoes.jar
WORKDIR /usr/src/sportyshoes
ENTRYPOINT ["java","-jar","sportyshoes.jar"]
#CMD ["jar", "-xf sportyshoes.jar"]
#CMD ["java","-jar","SportyShoes-0.0.1-SNAPSHOT.jar"]
#CMD ["java","-jar","sportyshoes.jar"]
